export const statusCarousel = [
    {
        img:"https://www.filmibeat.com/img/2020/03/untitled15-1584425670.jpg",
        name:"chaitanya"
    },
    {
        img:"https://th.bing.com/th/id/OIP.RMhsthDwNC1R-6f2_PUVKwHaE7?rs=1&pid=ImgDetMain",
        name:"ram"
    },
    {
        img:"https://www.thetelugufilmnagar.com/wp-content/uploads/2019/12/01.jpg",
        name:"prabhas"
    },
    {
        img:"https://th.bing.com/th/id/OIP.vSUsfgJ3O-4Xc4XIcsuYuAHaHa?rs=1&pid=ImgDetMain",
        name:"vdk"
    },
    {
        img:"https://th.bing.com/th/id/R.c6f0a36599f383fb55d1b62ee7a835ee?rik=MuCeo3WyBllV2A&riu=http%3a%2f%2fteluguone.com%2ftmdbuserfiles%2fntr(440).jpg&ehk=UuRLUGypn0J4u9J5UkqB2cBf7XyA79WgX%2bBmx5WMdrA%3d&risl=&pid=ImgRaw&r=0",
        name:"ntr"
    },
    {
        img:"https://th.bing.com/th/id/OIP.duT0TVYY1KGSRkAg6t_4owAAAA?w=423&h=423&rs=1&pid=ImgDetMain",
        name:"surya"
    },
    {
        img:"https://th.bing.com/th/id/OIP.Bwfl6If_Vd4aihkSMaPECwAAAA?w=404&h=319&rs=1&pid=ImgDetMain",
        name:"nani"
    },
    {
        img:"https://th.bing.com/th/id/OIP.ZcUgJJn8TOpECrt78QOtEgHaFj?w=799&h=600&rs=1&pid=ImgDetMain",
        name:"gopichand"
    },
    {
        img:"https://static.toiimg.com/thumb/msid-45727184,imgsize-34118,width-400,resizemode-4/45727184.jpg",
        name:"sudeep"
    }
]